import type {Atlas} from './anatomy';
import {GB_POINTS,needleProfile as gbNeedleProfile,type GbPointDefinition,type NeedleProfile,type NeedleRelation,type NeedleRegion,type ProjectionMode} from './gb-points';
import source from '../data/li-source.json';
import directNeedling from '../data/needling-direct.json';
import needlingReview from '../data/needling-review.json';
import needlingPaths from '../data/needling-paths.json';
import liLandmarks from '../data/li-landmarks.json';
import luData from '../data/meridians/LU.json';
import htData from '../data/meridians/HT.json';
import pcData from '../data/meridians/PC.json';
import stData from '../data/meridians/ST.json';
import spData from '../data/meridians/SP.json';
import siData from '../data/meridians/SI.json';
import blData from '../data/meridians/BL.json';
import kiData from '../data/meridians/KI.json';
import teData from '../data/meridians/TE.json';
import lrData from '../data/meridians/LR.json';
import cvData from '../data/meridians/CV.json';
import gvData from '../data/meridians/GV.json';

export const MERIDIANS = {
 LU:{id:'LU',label:'폐경',name:'수태음폐경',english:'LUNG MERIDIAN',count:11,first:'LU1'},
 LI:{id:'LI',label:'대장경',name:'수양명대장경',english:'LARGE INTESTINE MERIDIAN',count:20,first:'LI4'},
 ST:{id:'ST',label:'위경',name:'족양명위경',english:'STOMACH MERIDIAN',count:45,first:'ST36'},
 SP:{id:'SP',label:'비경',name:'족태음비경',english:'SPLEEN MERIDIAN',count:21,first:'SP6'},
 HT:{id:'HT',label:'심경',name:'수소음심경',english:'HEART MERIDIAN',count:9,first:'HT1'},
 SI:{id:'SI',label:'소장경',name:'수태양소장경',english:'SMALL INTESTINE MERIDIAN',count:19,first:'SI3'},
 BL:{id:'BL',label:'방광경',name:'족태양방광경',english:'BLADDER MERIDIAN',count:67,first:'BL40'},
 KI:{id:'KI',label:'신경',name:'족소음신경',english:'KIDNEY MERIDIAN',count:27,first:'KI3'},
 PC:{id:'PC',label:'심포경',name:'수궐음심포경',english:'PERICARDIUM MERIDIAN',count:9,first:'PC1'},
 TE:{id:'TE',label:'삼초경',name:'수소양삼초경',english:'TRIPLE ENERGIZER MERIDIAN',count:23,first:'TE5'},
 GB:{id:'GB',label:'담경',name:'족소양담경',english:'GALLBLADDER MERIDIAN',count:44,first:'GB34'},
 LR:{id:'LR',label:'간경',name:'족궐음간경',english:'LIVER MERIDIAN',count:14,first:'LR3'},
 CV:{id:'CV',label:'임맥',name:'임맥',english:'CONCEPTION VESSEL',count:24,first:'CV8'},
 GV:{id:'GV',label:'독맥',name:'독맥',english:'GOVERNOR VESSEL',count:28,first:'GV20'},
} as const;
export type MeridianId = keyof typeof MERIDIANS;
export type AcupointCode = `${MeridianId}${number}`;
export type NeedlingReviewStatus='open'|'review_required'|'locked';
export type AcupointDefinition = Omit<GbPointDefinition,'code'|'verifiedOn'> & {
 code:AcupointCode; verifiedOn:string; outward?:[number,number,number];
 rawLocation?:string; alternative?:string; sourceStatus?:string; rule?:string;
};
const WHO='https://iris.who.int/handle/10665/353407';
const english=['Shangyang','Erjian','Sanjian','Hegu','Yangxi','Pianli','Wenliu','Xialian','Shanglian','Shousanli','Quchi','Zhouliao','Shouwuli','Binao','Jianyu','Jugu','Tianding','Futu','Kouheliao','Yingxiang'];

/**
 * Right-side skin anchors generated offline by scripts/li-landmarks.mjs from bone/muscle
 * vertices (KCMRIC primary, WHO 2008 secondary). Still review status, not clinical truth.
 */
export function buildLiPoints(_atlas?:Atlas):AcupointDefinition[] {
 return source.points.map((row,index)=>{
  const number=index+1,match=row.name.match(/^([^（(]+)[（(]([^）)]+)/)!;
  const anchor=liLandmarks.points[row.code as keyof typeof liLandmarks.points];
  if(!anchor)throw new Error('LI landmark missing: '+row.code);
  return {code:row.code as AcupointCode,korean:match[1].trim(),hanja:match[2],english:english[index],
   location:row.canonicalLocation,basis:'골격·근육 정점 기반 랜드마크 · '+anchor.rule,seed:anchor.seed as [number,number,number],
   projection:number>=19?'anterior':'lateral',outward:anchor.outward as [number,number,number],status:'review',
   primarySource:row.source,secondarySource:source.sourceFile,verifiedOn:'',
   rawLocation:row.rawLocation,alternative:row.alternative,sourceStatus:row.sourceStatus,rule:row.rule};
 });
}

/** Meridians generated by scripts/meridians/<id>.mjs → data/meridians/<ID>.json (raw text kept beside each rule). */
interface GeneratedPoint{code:string;korean:string;hanja:string;english:string;location:string;rawLocation:string;rawMethod:string;whoStatus:string;whoNote:string;status:string;seed:number[];outward:number[];region:string;rule:string;projection?:ProjectionMode;needlingStatus?:string;needlingRestriction?:string}
interface GeneratedMeridian{id:string;primarySource:string;points:GeneratedPoint[]}
const GENERATED:GeneratedMeridian[]=[luData,htData,pcData,stData,spData,siData,blData,kiData,teData,lrData,cvData,gvData] as GeneratedMeridian[];
const generatedRow=(code:string)=>GENERATED.flatMap(meridian=>meridian.points).find(point=>point.code===code);
function buildGeneratedPoints(meridian:GeneratedMeridian):AcupointDefinition[]{
 return meridian.points.map(point=>({code:point.code as AcupointCode,korean:point.korean,hanja:point.hanja,english:point.english,
  location:point.location,basis:'골격·근육 정점 기반 랜드마크 · '+point.rule,seed:point.seed as [number,number,number],
  projection:point.projection??'lateral',outward:point.outward as [number,number,number],status:'review',
  primarySource:`${meridian.primarySource}/${point.code}`,secondarySource:WHO,verifiedOn:'',
  rawLocation:point.rawLocation,alternative:'',sourceStatus:point.status,rule:point.rule}));
}

export const ALL_POINTS:AcupointDefinition[]=[...GB_POINTS,...buildLiPoints(),...GENERATED.flatMap(buildGeneratedPoints)];
export const RELEASE_POINT_NOTE='361혈을 모두 표시합니다. 위치 검수 중인 혈은 학습용 모델 좌표이며, 실제 사람의 촉진·취혈을 대신하지 않습니다.';
export function atlasPoints(_atlas?:Atlas):AcupointDefinition[]{return ALL_POINTS;}
export function meridianOf(code:string):MeridianId{const prefix=code.match(/^[A-Z]+/)?.[0];return prefix&&prefix in MERIDIANS?prefix as MeridianId:'GB';}
const needleRegionOf=(skinRegion:string):NeedleRegion=>/thorax|shoulder/.test(skinRegion)?'thorax':/face|head|oral/.test(skinRegion)?'face-scalp':/neck/.test(skinRegion)?'neck':/lumbar|pelvis/.test(skinRegion)?'flank-abdomen':/thigh|knee/.test(skinRegion)?'thigh-knee':/leg/.test(skinRegion)?'leg':/foot/.test(skinRegion)?'ankle-foot':'upper-limb';
// Compared against the primary workbook's straight-path model rows (repo 2d4aa8e).
// A structure missing from the model path is a model limit, never permission to needle.
// LI18, ST9, ST36, BL40 and GB20 moved to data/needling-paths.json hazards (review 2026-09-25).
const PATH_NOTES:Partial<Record<AcupointCode,string>>={
 SI16:'이 모델의 직자 경로에는 목의 큰 혈관이 나타나지 않지만, 실제로는 가까이 있습니다.',
 TE16:'이 모델의 직자 경로에는 목의 큰 혈관이 나타나지 않지만, 실제로는 가까이 있습니다.',
 GV16:'이 모델의 직자 경로는 뒤통수뼈에 먼저 닿습니다. 실제로는 깊은 곳에 경막과 연수가 있습니다.',
 CV12:'이 모델에는 복막이 없어, 배벽 다음에 바로 위(胃)가 나타납니다.',
};
/** Points the source records as forbidden to needle outright: the simulation stays locked.
 *  Straight-needle points come from data/needling-direct.json (noNeedling); ST17 has no technique at all. */
const NO_NEEDLING:Partial<Record<AcupointCode,string>>={ST17:'禁鍼 (『鍼灸甲乙經』)',CV8:'禁鍼穴'};
const noNeedlingOf=(code:AcupointCode)=>NO_NEEDLING[code];
const NEEDLING_REVIEW=new Map(needlingReview.map(row=>[row.point,row]));
export function needlingReviewOf(code:AcupointCode){return NEEDLING_REVIEW.get(code) as (typeof needlingReview)[number]&{status:NeedlingReviewStatus};}
const STRAIGHT_WARNING='오른쪽 참조 모델에서 피부에 수직으로 찌른 경로입니다. 문헌의 촌 범위를 이 모델의 비례 치수로 환산한 값이며, 임상에서의 안전 깊이가 아닙니다.';
const lockedProfile=(region:NeedleRegion,warning:string,sourceNeedling:string,validationSource:string,pointRisk?:string):NeedleProfile=>
 ({region,label:'자침 시뮬레이션 없음',probeDepthMm:0,conceptualBoundary:false,warning,sourceNeedling,depthValidation:'시뮬레이션 없음',validationSource,referenceStructures:[],pointRisk});
/** LI3 gives a depth without naming the technique, BL61 says "直刺 or 斜刺", GV22 only "刺", ST7 lists moxibustion only. */
const NO_STRAIGHT='문헌 자침법에서 직자 깊이를 확정할 수 없어 자침 시뮬레이션을 제공하지 않습니다.';
const forbiddenWarning=(source:string)=>`문헌에 금침혈로 기록되어 있습니다 — ${source}. 자침 시뮬레이션을 제공하지 않습니다.`;
// Only relationships explicitly supported by the primary workbook's expected_anatomy.
const RESEARCH_RELATIONS:Partial<Record<AcupointCode,NeedleRelation[]>>={
 LI18:[{kind:'AVOID',structure:'주요 경부 혈관'}],
 ST9:[{kind:'AVOID',structure:'총경동맥'}],
 ST36:[{kind:'INTERSECT',structure:'앞정강근'},{kind:'APPROACH',structure:'심비골신경'},{kind:'AVOID',structure:'전경골동맥'}],
 SI14:[{kind:'AVOID',structure:'흉막'}],SI15:[{kind:'AVOID',structure:'흉막'}],
 SI16:[{kind:'AVOID',structure:'주요 경부 혈관'}],SI17:[{kind:'AVOID',structure:'주요 경부 혈관'}],
 BL40:[{kind:'AVOID',structure:'슬와동맥'}],
 PC6:[{kind:'INTERSECT',structure:'천지굴근·심지굴근·방형회내근'},{kind:'APPROACH',structure:'정중신경'}],
 TE16:[{kind:'AVOID',structure:'주요 경부 혈관'}],
 GB20:[{kind:'AVOID',structure:'주요 경부 혈관'}],GB21:[{kind:'AVOID',structure:'흉막'}],
 GV15:[{kind:'AVOID',structure:'경막'}],GV16:[{kind:'AVOID',structure:'경막'}],
 CV12:[{kind:'AVOID',structure:'복막'}],
};
const riskText=(...parts:(string|undefined)[])=>parts.filter(Boolean).join(' ')||undefined;
/** Reviewed path of a multi-layer point (scripts/needling/build-needle-paths.mjs, review of 2026-09-25).
 *  Layers are superficial→deep; a layer without mm is a concept layer (no mesh, or out of order in the
 *  model) placed by anatomical sequence. Hazards are never passed layers: the panel lists them apart. */
export interface NeedlePathLayer{ko:string;en:string;mm:number|null;end:number|null;kind:'model'|'concept'|'reordered'|'void';atlas?:string;why?:string}
export interface NeedlePathHazard{ko:string;en:string;mm:number|null;source:'model'|'literature'|'concept';relation:'cross'|'near'|'concept';emph?:boolean;note?:string;basis?:string;literatureMm?:number}
export interface NeedlePath{region:string;blocked?:string;direction?:[number,number,number];directionBasis?:string;faceDeviationDeg?:number;layers?:NeedlePathLayer[];hazards?:NeedlePathHazard[];bone?:{ko:string;en:string;mm:number};dropped?:{names:string[];why?:string};note?:string;posture?:string;zone?:string;modelMaxMm?:number|null}
const NEEDLE_PATHS=needlingPaths as unknown as Record<string,NeedlePath>;
export function needlePathOf(code:string):NeedlePath|undefined{return code.startsWith('_')?undefined:NEEDLE_PATHS[code];}
function sourceNeedleProfile(code:AcupointCode):NeedleProfile {
 const reviewed=needlePathOf(code);
 if(reviewed?.blocked)return lockedProfile(needleRegionOf(reviewed.region==='neck'?'neck':'thorax'),reviewed.blocked,directNeedling[code as keyof typeof directNeedling]?.raw??'',`https://m.kmcric.com/knowledge/acupoint/${meridianOf(code)}/${code}`);
 const direct=directNeedling[code as keyof typeof directNeedling];
 const forbiddenSource=noNeedlingOf(code);
 const straight=direct&&!forbiddenSource?{label:'문헌 직자 범위의 모델 상한',probeDepthMm:direct.modelMaxMm,documentedMaxMm:direct.modelMaxMm,
  depthRangeCun:[direct.minCun,direct.maxCun] as [number,number],conceptualBoundary:false,warning:STRAIGHT_WARNING,
  sourceNeedling:direct.raw,depthValidation:'문헌 범위 · 모델 비율 환산',relations:RESEARCH_RELATIONS[code]}:undefined;
 if(code.startsWith('GB')){const profile=gbNeedleProfile(code as `GB${number}`);
  if(!straight)return lockedProfile(profile.region,forbiddenSource?forbiddenWarning(forbiddenSource):NO_STRAIGHT,profile.sourceNeedling,profile.validationSource);
  return {...profile,...straight,pointRisk:riskText(profile.pointRisk,direct?.caution,PATH_NOTES[code])};}
 const generated=generatedRow(code);
 if(generated){
  const meridian=MERIDIANS[meridianOf(code)],validationSource=`https://m.kmcric.com/knowledge/acupoint/${meridian.id}/${code}`,region=needleRegionOf(generated.region);
  if(generated.needlingStatus==='absolute_no_needling'||forbiddenSource)
   return lockedProfile(region,forbiddenWarning(forbiddenSource??'禁鍼穴'),direct?.raw??forbiddenSource??'禁鍼穴',validationSource);
  if(straight)return {region,...straight,validationSource,referenceStructures:[],pointRisk:riskText(direct?.caution,generated.needlingRestriction,PATH_NOTES[code])};
  return lockedProfile(region,generated.needlingRestriction?`${generated.needlingRestriction} 이 혈은 자침 시뮬레이션을 제공하지 않습니다.`:NO_STRAIGHT,
   '문헌 직자 깊이 없음',validationSource);
 }
 const row=source.points.find(p=>p.code===code)!;
 const liRegion:NeedleRegion=Number(code.slice(2))>=19?'face-scalp':Number(code.slice(2))>=17?'neck':'upper-limb';
 if(straight)return {region:liRegion,...straight,validationSource:row.source,referenceStructures:[],pointRisk:riskText(direct?.caution,PATH_NOTES[code])};
 return lockedProfile(liRegion,forbiddenSource?forbiddenWarning(forbiddenSource):NO_STRAIGHT,
  row.rawNeedling||'문헌 직자 깊이 없음',row.source,row.rawMethod||undefined);
}

export function needleProfile(code:AcupointCode):NeedleProfile{
 const reviewed=needlePathOf(code),base=sourceNeedleProfile(code),review=needlingReviewOf(code);
 const source=reviewed&&!reviewed.blocked?{...base,pointRisk:riskText(base.pointRisk,reviewed.posture,reviewed.note)}:base;
 if(review.status!=='review_required')return source;
 return {...source,label:`검수용 · ${source.label}`,
  depthValidation:`${source.depthValidation} · 배포 승인 대기`,warning:`검수용 경로입니다. 승인 전에는 배포 공개되지 않습니다. ${source.warning}`};
}
