import type {Atlas} from './anatomy';
import {GB_POINTS,needleProfile as gbNeedleProfile,type GbPointDefinition,type NeedleProfile,type NeedleRelation,type NeedleRegion,type ProjectionMode} from './gb-points';
import source from '../data/li-source.json';
import directNeedling from '../data/needling-direct.json';
import liLandmarks from '../data/li-landmarks.json';
import luData from '../data/meridians/LU.json';
import htData from '../data/meridians/HT.json';
import pcData from '../data/meridians/PC.json';
import stData from '../data/meridians/ST.json';
import spData from '../data/meridians/SP.json';
import siData from '../data/meridians/SI.json';
import blData from '../data/meridians/BL.json';
import kiData from '../data/meridians/KI.json';
import teData from '../data/meridians/TE.json';
import lrData from '../data/meridians/LR.json';
import cvData from '../data/meridians/CV.json';
import gvData from '../data/meridians/GV.json';

export const MERIDIANS = {
 LU:{id:'LU',label:'폐경',name:'수태음폐경',english:'LUNG MERIDIAN',count:11,first:'LU1'},
 LI:{id:'LI',label:'대장경',name:'수양명대장경',english:'LARGE INTESTINE MERIDIAN',count:20,first:'LI4'},
 ST:{id:'ST',label:'위경',name:'족양명위경',english:'STOMACH MERIDIAN',count:45,first:'ST36'},
 SP:{id:'SP',label:'비경',name:'족태음비경',english:'SPLEEN MERIDIAN',count:21,first:'SP6'},
 HT:{id:'HT',label:'심경',name:'수소음심경',english:'HEART MERIDIAN',count:9,first:'HT1'},
 SI:{id:'SI',label:'소장경',name:'수태양소장경',english:'SMALL INTESTINE MERIDIAN',count:19,first:'SI3'},
 BL:{id:'BL',label:'방광경',name:'족태양방광경',english:'BLADDER MERIDIAN',count:67,first:'BL40'},
 KI:{id:'KI',label:'신경',name:'족소음신경',english:'KIDNEY MERIDIAN',count:27,first:'KI3'},
 PC:{id:'PC',label:'심포경',name:'수궐음심포경',english:'PERICARDIUM MERIDIAN',count:9,first:'PC1'},
 TE:{id:'TE',label:'삼초경',name:'수소양삼초경',english:'TRIPLE ENERGIZER MERIDIAN',count:23,first:'TE5'},
 GB:{id:'GB',label:'담경',name:'족소양담경',english:'GALLBLADDER MERIDIAN',count:44,first:'GB34'},
 LR:{id:'LR',label:'간경',name:'족궐음간경',english:'LIVER MERIDIAN',count:14,first:'LR3'},
 CV:{id:'CV',label:'임맥',name:'임맥',english:'CONCEPTION VESSEL',count:24,first:'CV8'},
 GV:{id:'GV',label:'독맥',name:'독맥',english:'GOVERNOR VESSEL',count:28,first:'GV20'},
} as const;
export type MeridianId = keyof typeof MERIDIANS;
export type AcupointCode = `${MeridianId}${number}`;
export type AcupointDefinition = Omit<GbPointDefinition,'code'|'verifiedOn'> & {
 code:AcupointCode; verifiedOn:string; outward?:[number,number,number];
 rawLocation?:string; alternative?:string; sourceStatus?:string; rule?:string;
};
const WHO='https://iris.who.int/handle/10665/353407';
const english=['Shangyang','Erjian','Sanjian','Hegu','Yangxi','Pianli','Wenliu','Xialian','Shanglian','Shousanli','Quchi','Zhouliao','Shouwuli','Binao','Jianyu','Jugu','Tianding','Futu','Kouheliao','Yingxiang'];

/**
 * Right-side skin anchors generated offline by scripts/li-landmarks.mjs from bone/muscle
 * vertices (KCMRIC primary, WHO 2008 secondary). Still review status, not clinical truth.
 */
export function buildLiPoints(_atlas?:Atlas):AcupointDefinition[] {
 return source.points.map((row,index)=>{
  const number=index+1,match=row.name.match(/^([^（(]+)[（(]([^）)]+)/)!;
  const anchor=liLandmarks.points[row.code as keyof typeof liLandmarks.points];
  if(!anchor)throw new Error('LI landmark missing: '+row.code);
  return {code:row.code as AcupointCode,korean:match[1].trim(),hanja:match[2],english:english[index],
   location:row.canonicalLocation,basis:'골격·근육 정점 기반 랜드마크 · '+anchor.rule,seed:anchor.seed as [number,number,number],
   projection:number>=19?'anterior':'lateral',outward:anchor.outward as [number,number,number],status:'review',
   primarySource:row.source,secondarySource:source.sourceFile,verifiedOn:'',
   rawLocation:row.rawLocation,alternative:row.alternative,sourceStatus:row.sourceStatus,rule:row.rule};
 });
}

/** Meridians generated by scripts/meridians/<id>.mjs → data/meridians/<ID>.json (raw text kept beside each rule). */
interface GeneratedPoint{code:string;korean:string;hanja:string;english:string;location:string;rawLocation:string;rawMethod:string;whoStatus:string;whoNote:string;status:string;seed:number[];outward:number[];region:string;rule:string;projection?:ProjectionMode;needlingStatus?:string;needlingRestriction?:string}
interface GeneratedMeridian{id:string;primarySource:string;points:GeneratedPoint[]}
const GENERATED:GeneratedMeridian[]=[luData,htData,pcData,stData,spData,siData,blData,kiData,teData,lrData,cvData,gvData] as GeneratedMeridian[];
const generatedRow=(code:string)=>GENERATED.flatMap(meridian=>meridian.points).find(point=>point.code===code);
function buildGeneratedPoints(meridian:GeneratedMeridian):AcupointDefinition[]{
 return meridian.points.map(point=>({code:point.code as AcupointCode,korean:point.korean,hanja:point.hanja,english:point.english,
  location:point.location,basis:'골격·근육 정점 기반 랜드마크 · '+point.rule,seed:point.seed as [number,number,number],
  projection:point.projection??'lateral',outward:point.outward as [number,number,number],status:'review',
  primarySource:`${meridian.primarySource}/${point.code}`,secondarySource:WHO,verifiedOn:'',
  rawLocation:point.rawLocation,alternative:'',sourceStatus:point.status,rule:point.rule}));
}

export function atlasPoints(atlas:Atlas):AcupointDefinition[]{return [...GB_POINTS,...buildLiPoints(atlas),...GENERATED.flatMap(buildGeneratedPoints)];}
export function meridianOf(code:string):MeridianId{const prefix=code.match(/^[A-Z]+/)?.[0];return prefix&&prefix in MERIDIANS?prefix as MeridianId:'GB';}
const needleRegionOf=(skinRegion:string):NeedleRegion=>/thorax|shoulder/.test(skinRegion)?'thorax':/face|head|oral/.test(skinRegion)?'face-scalp':/neck/.test(skinRegion)?'neck':/lumbar|pelvis/.test(skinRegion)?'flank-abdomen':/thigh|knee/.test(skinRegion)?'thigh-knee':/leg/.test(skinRegion)?'leg':/foot/.test(skinRegion)?'ankle-foot':'upper-limb';
// Compared against the primary workbook's straight-path model rows (repo 2d4aa8e).
// A missing AVOID intersection is a geometry QC finding, never permission to needle.
const PATH_QC:Partial<Record<AcupointCode,string>>={
 LI18:'모델 QC: 주요 경부 혈관이 직자 궤적과 교차하지 않습니다.',
 ST9:'모델 QC: 문헌 표지인 경동맥이 직자 궤적과 교차하지 않습니다.',
 ST36:'모델 QC: 문헌 표지인 전경골동맥이 직자 궤적에 나타나지 않습니다.',
 SI16:'모델 QC: 주요 경부 혈관이 직자 궤적과 교차하지 않습니다.',
 SI17:'모델 QC: 주요 경부 혈관이 직자 궤적과 교차하지 않습니다.',
 BL40:'모델 QC: 문헌 표지인 슬와동맥 대신 슬와정맥이 궤적에 나타납니다.',
 TE16:'모델 QC: 주요 경부 혈관이 직자 궤적과 교차하지 않습니다.',
 GB20:'모델 QC: 경부 혈관 전에 후두골이 교차합니다. 문헌의 혈관 거리와 비교할 수 없습니다.',
 GB21:'모델 QC: 흉막 전에 상완골이 교차합니다. 문헌의 흉막 거리를 이 경로에 적용할 수 없습니다.',
 GV16:'모델 QC: 문헌 표지인 경막은 궤적에 없고 후두골이 먼저 교차합니다.',
 CV12:'모델 QC: 문헌 표지인 복막 메시가 궤적에 없으며 위가 교차합니다.',
};
// Only relationships explicitly supported by the primary workbook's expected_anatomy.
const RESEARCH_RELATIONS:Partial<Record<AcupointCode,NeedleRelation[]>>={
 LI18:[{kind:'AVOID',structure:'주요 경부 혈관'}],
 ST9:[{kind:'AVOID',structure:'총경동맥'}],
 ST36:[{kind:'INTERSECT',structure:'앞정강근'},{kind:'APPROACH',structure:'심비골신경'},{kind:'AVOID',structure:'전경골동맥'}],
 SI14:[{kind:'AVOID',structure:'흉막'}],SI15:[{kind:'AVOID',structure:'흉막'}],
 SI16:[{kind:'AVOID',structure:'주요 경부 혈관'}],SI17:[{kind:'AVOID',structure:'주요 경부 혈관'}],
 BL40:[{kind:'AVOID',structure:'슬와동맥'}],
 PC6:[{kind:'INTERSECT',structure:'천지굴근·심지굴근·방형회내근'},{kind:'APPROACH',structure:'정중신경'}],
 TE16:[{kind:'AVOID',structure:'주요 경부 혈관'}],
 GB20:[{kind:'AVOID',structure:'주요 경부 혈관'}],GB21:[{kind:'AVOID',structure:'흉막'}],
 GV15:[{kind:'AVOID',structure:'경막'}],GV16:[{kind:'AVOID',structure:'경막'}],
 CV12:[{kind:'AVOID',structure:'복막'}],
};
const riskText=(...parts:(string|undefined)[])=>parts.filter(Boolean).join(' ')||undefined;
export function needleProfile(code:AcupointCode):NeedleProfile {
 const direct=directNeedling[code as keyof typeof directNeedling];
 if(code.startsWith('GB')){const profile=gbNeedleProfile(code as `GB${number}`);return {...profile,
  ...(direct?{label:'문헌 직자 범위의 모델 상한',probeDepthMm:direct.modelMaxMm,documentedMaxMm:direct.modelMaxMm,
   depthRangeCun:[direct.minCun,direct.maxCun] as [number,number],conceptualBoundary:false,
   warning:'참조 모델의 체표 법선 직자 경로입니다. 문헌 촌 범위를 이 모델의 국소 비례치로 환산했으며 임상 안전심도가 아닙니다.',
   sourceNeedling:direct.raw,depthValidation:'문헌 범위 · 모델 비율 환산'}:{}),
  relations:RESEARCH_RELATIONS[code],pointRisk:riskText(profile.pointRisk,direct?.caution,PATH_QC[code])};}
 const generated=generatedRow(code);
 if(generated){
  const meridian=MERIDIANS[meridianOf(code)];
  const forbidden=generated.needlingStatus==='absolute_no_needling';
  const caution=generated.needlingRestriction||`${meridian.label} 위치는 검수 완료했지만 자침 방향·깊이는 3D에서 미검증입니다.`;
  if(direct&&!forbidden)return {region:needleRegionOf(generated.region),label:'문헌 직자 범위의 모델 상한',probeDepthMm:direct.modelMaxMm,
   documentedMaxMm:direct.modelMaxMm,depthRangeCun:[direct.minCun,direct.maxCun],conceptualBoundary:false,
   warning:'참조 모델의 체표 법선 직자 경로입니다. 문헌 촌 범위를 이 모델의 국소 비례치로 환산했으며 임상 안전심도가 아닙니다.',
   sourceNeedling:direct.raw,depthValidation:'문헌 범위 · 모델 비율 환산',
   validationSource:`https://m.kmcric.com/knowledge/acupoint/${meridian.id}/${code}`,
   referenceStructures:[generated.rule],relations:RESEARCH_RELATIONS[code],pointRisk:riskText(direct.caution,generated.needlingRestriction,PATH_QC[code])};
  return {region:needleRegionOf(generated.region),label:`${meridian.id} 자침 경로 미검증`,probeDepthMm:0,conceptualBoundary:false,
   warning:forbidden?'자침 금지: 신궐(CV8)은 금침혈이며 자침 시뮬레이션을 제공하지 않습니다.':`${caution} 자침 경로·깊이가 검증되기 전에는 시뮬레이션을 제공하지 않습니다.`,
   sourceNeedling:generated.rawMethod||'깊이 미검증',depthValidation:'미검증 · 시뮬레이션 잠금',
   validationSource:`https://m.kmcric.com/knowledge/acupoint/${meridian.id}/${code}`,referenceStructures:[generated.rule],pointRisk:generated.needlingRestriction||generated.whoStatus||undefined};
 }
 const row=source.points.find(p=>p.code===code)!;
 if(direct)return {region:Number(code.slice(2))>=19?'face-scalp':Number(code.slice(2))>=17?'neck':'upper-limb',
  label:'문헌 직자 범위의 모델 상한',probeDepthMm:direct.modelMaxMm,documentedMaxMm:direct.modelMaxMm,
  depthRangeCun:[direct.minCun,direct.maxCun],conceptualBoundary:false,
  warning:'참조 모델의 체표 법선 직자 경로입니다. 문헌 촌 범위를 이 모델의 국소 비례치로 환산했으며 임상 안전심도가 아닙니다.',
  sourceNeedling:direct.raw,depthValidation:'문헌 범위 · 모델 비율 환산',validationSource:row.source,
  referenceStructures:[row.region],relations:RESEARCH_RELATIONS[code],pointRisk:riskText(direct.caution,PATH_QC[code])};
 return {region:Number(code.slice(2))>=19?'face-scalp':Number(code.slice(2))>=17?'neck':'upper-limb',
  label:'LI 자침 경로 미검증',probeDepthMm:0,conceptualBoundary:false,
  warning:'LI 위치·지역 프레임은 검수 중입니다. 자침 방향·깊이가 검증되기 전에는 자침 시뮬레이션을 제공하지 않습니다.',
  sourceNeedling:row.rawNeedling||'깊이 미검증',depthValidation:'미검증 · 시뮬레이션 잠금',
  validationSource:row.source,referenceStructures:[row.region],pointRisk:row.rawMethod||undefined};
}
